apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: products
spec:
  # NodePort 30080 is mapped to host (EC2) port 8080 by kind-config.yaml
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
